import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Montserrat_Alternates,
  Raleway,
} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montseAlter = Montserrat_Alternates({
  weight: ["400"],
  style: "normal",
  variable: "--font-Montserrat",
  subsets: ["latin"],
});

const geistRaleway = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create C&J",
  description: "Generated by create CRLS",
};

//https://img.freepik.com/vector-gratis/diseno-abstracto-fondo_1107-155.jpg
//https://www.microtech.es/hubfs/erp_mantenimiento.jpg
//https://marq.mx/wp-content/uploads/2020/08/17-de-AGO-El-mantenimiento-aumenta-el-valor-de-las-viviendas.jpg
//https://ceicid.es/wp-content/uploads/2023/07/banner-curso-mantenimiento-23.jpg

const bag3 = "https://github.com/CRLSsanz/trade/blob/main/fondo01.jpg?raw=true";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={` ${geistRaleway.className} antialiased`}>
        <div
          id="sectionHome"
          className="w-full flex justify-center bg-cover bg-fixed bg-[50%] Xbg-[url('https://img.freepik.com/vector-gratis/fondo-abstracto-borroso_1107-166.jpg')] min-h-screen"
        >
          {children}
        </div>

        <section
          id="section6"
          className="bg-[#259ca0] flex"
          style={{
            backgroundImage: `linear-gradient(rgba(0,0,0,9), rgba(0,0,0,0.85)), url(${bag3})`,
            backgroundPosition: "50% 20%",
            backgroundSize: "cover",
            //backgroundAttachment: "fixed",
          }}
        >
          <div className="my-autooo w-full">
            <h1 className="h-16"> </h1>
            <Footer />
          </div>
        </section>

        {/** COPYRIGHT */}
        <div className="BBbg-[#050505] bg-gray-50 text-gray-500 text-center text-sm py-4 ">
          <h4 className="px-12 tracking-wider">
            © <span className="fam-number font-extralight">2020-2026 </span>{" "}
            Reformas C&J™ | All Rights Reserved.
            <span className="hidden">Designed by CRLSCODE</span>
          </h4>
        </div>
      </body>
    </html>
  );
}
